jwt:
    issuer: under912@naver.com
    secret: nhJoeH7FctPVlEKToZJw3hjF609SJDSE
logging:
    file:
        name: /logs/sboard.log
    level:
        jdbc:
            sqlonly: debug
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
                sql: debug
        resultsettable: debug
        root: info
        sqltiming: debug
server:
    port: 8080
    servlet:
        context-path: /sboard
spring:

    application:
        name: sboard
        version: 0.0.2
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Wnrud1234!
        url: jdbc:mysql://15.164.70.236:3306/sboard
        username: sboard
    devtools:
        livereload:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    mail:
        username: jptrnmrs@gmail.com
        password: diog dhjo yxdt gcpb

    thymeleaf:
        prefix: classpath:/templates